name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      STRIPE_PUBLISHABLE: ${{ secrets.STRIPE_PUBLISHABLE }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Transpile TypeScript files
        run: npm run build
      - name: Install Playwright
        run: npx playwright install
      - name: Run tests
        run: npm test
